apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mizar-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: mizar-operator
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mizar-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mizar-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mizar-operator
  template:
    metadata:
      labels:
        app: mizar-operator
        mizar: operator
    spec:
      serviceAccountName: mizar-operator
      hostNetwork: true
      tolerations:
        - operator: Exists
          effect: NoSchedule
      containers:
        - image: clu2docker/endpointopr:latest
          name: mizar-operator
          securityContext:
            privileged: true
