apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dividers.mizar.com
spec:
  scope: Namespaced
  group: mizar.com
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: Divider
    plural: dividers
    singular: divider
    shortNames:
      - divd
      - divds
  additionalPrinterColumns:
    - name: vpc
      type: string
      priority: 0
      JSONPath: .spec.vpc
      description: The VPC of the divider
    - name: Ip
      type: string
      priority: 0
      JSONPath: .spec.ip
      description: The IP of the divider's droplet
    - name: Mac
      type: string
      priority: 0
      JSONPath: .spec.mac
      description: The mac address of the divider's droplet
    - name: Droplet
      type: string
      priority: 0
      JSONPath: .spec.droplet
      description: The name of the droplet resource
    - name: Status
      type: string
      priority: 0
      JSONPath: .spec.status
      description: The Current Status of the divider