apiVersion: apps/v1
kind: Deployment
metadata:
  name: mizar-operator
spec:
  selector:
    matchLabels:
      app: mizar-operator
  template:
    metadata:
      labels:
        app: mizar-operator
    spec:
      serviceAccountName: mizar-operator
      hostNetwork: true
      containers:
      - image: selgohari/endpointopr:latest
        name: mizar-operator
        securityContext:
            privileged: true