apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bouncers.mizar.com
spec:
  scope: Namespaced
  group: mizar.com
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: Bouncer
    plural: bouncers
    singular: bouncer
    shortNames:
      - bncr
      - bncrs
  additionalPrinterColumns:
    - name: Ip
      type: string
      priority: 0
      JSONPath: .spec.ip
      description: The IP of the endpoint
    - name: Droplet
      type: string
      priority: 0
      JSONPath: .spec.droplet
      description: The name of the droplet resource