apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: endpoints.mizar.com
spec:
  scope: Namespaced
  group: mizar.com
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: Endpoint
    plural: endpoints
    singular: endpoint
    shortNames:
      - ep
      - eps
  additionalPrinterColumns:
    - name: Type
      type: string
      priority: 0
      JSONPath: .spec.type
      description: The type of the endpoint
    - name: Mac
      type: string
      priority: 0
      JSONPath: .spec.mac
      description: The mac address of the endpoint
    - name: Ip
      type: string
      priority: 0
      JSONPath: .spec.ip
      description: The IP of the endpoint
    - name: Gw
      type: string
      priority: 0
      JSONPath: .spec.gw
      description: The GW of the endpoint
    - name: Status
      type: string
      priority: 0
      JSONPath: .spec.status
      description: The Current Provisioning Status of the endpoint
    - name: Network
      type: string
      priority: 0
      JSONPath: .spec.net
      description: The network of the endpoint
    - name: Vpc
      type: string
      priority: 0
      JSONPath: .spec.vpc
      description: The vpc of the endpoint
    - name: Vni
      type: string
      priority: 0
      JSONPath: .spec.vni
      description: The VNI of the VPC
    - name: Droplet
      type: string
      priority: 0
      JSONPath: .spec.droplet
      description: The droplet hosting the endpoint
