apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nets.mizar.com
spec:
  scope: Namespaced
  group: mizar.com
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: Net
    plural: nets
    singular: net
    shortNames:
      - net
      - nets
  additionalPrinterColumns:
    - name: Ip
      type: string
      priority: 0
      JSONPath: .spec.ip
      description: The IP of the VPC CIDR block
    - name: Prefix
      type: string
      priority: 0
      JSONPath: .spec.prefix
      description: The prefix of the VPC CIDR block
    - name: Vni
      type: string
      priority: 0
      JSONPath: .spec.vni
      description: The VNI of the VPC
    - name: Vpc
      type: string
      priority: 0
      JSONPath: .spec.vpc
      description: The name of the VPC
